# Generated by Django 5.2.7 on 2025-10-11 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('image_file', models.ImageField(null=True, upload_to='article_images/')),
                ('article', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='produits.article')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('image_file', models.ImageField(null=True, upload_to='produit_images/')),
                ('produit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='produits.produit')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
