# Generated by Django 5.2.7 on 2025-10-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_remove_article_categorie_article_produit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagesProduit',
        ),
    ]
