# Generated by Django 5.2.7 on 2025-10-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_commande_articlecommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='nom_client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
